### ISSUE TITLE
Make it possible to send to multiple Slack channels

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/botf#1]
Would prefer if this change does not break current implementations. 

This is how we do it in the OTF WebApp: 

~~~~ python
        data = {
            "room": target_room,
            "message": message,
        }
        response = requests.post(self.destination, json=data)
~~~~

The "target_room" variable is a string. If the new code that detect that and work as now if it's a string and send to multiple channels if it's e.g. an array would be good I think.

**Comment by jheretic** [comment]
@frjo I was aiming for sometime before the next sprint starts on Monday.

**Comment by jheretic** [comment]
This functionality is now enabled on the live bot. The "room" attribute now supports receiving both strings (for single targets) and arrays of strings (for multiple target rooms). For example with curl:
```
curl -X POST -H "Content-Type: application/json" -d '{"room": ["#channel1", "#channel2"], "message": "test"}' https://<bot URL>/incoming/<token>
```
